dist: trusty
language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - sudo redis-server -p 6380
script:
  - pipenv run flake8 --ignore=E501
  - pipenv run celery multi start w1 -A tasks worker --loglevel=info
  - pipenv run python trigger.py
  - pipenv run celery multi stop w1 -A tasks worker --loglevel=info
