dist: trusty
language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run flake8 --ignore=E501
  - pipenv run celery multi start w1 -A tasks worker --loglevel=info
  - pipenv run trigger.py
  pipenv run celery multi stop w1 -A tasks worker --loglevel=info
services:
  - redis-server -p 6380
